### PR TITLE
Add Missing Trailing Newlines in Logs

### PR DESCRIPTION
**Pull request by ben9923**
Those logs were printed together with other random system logs in the same lines :/

### CODE REVIEW

**Review by kprinssu — APPROVED** [review]
Looks good. Do we need to update the other IOLogs calls across the project as well?

**Comment by 1Revenger1** [comment]
All IOLog statements should have new lines on them
I ended up creating a [macro for it](https://github.com/VoodooSMBus/VoodooRMI/blob/90d313d29eca1e2b335b59d057100d370c61f489/VoodooRMI/Utility/Logging.h#L15) in VRMI.
May also be able to put in getName() in there as well if you wanted, doesn't work when outside an IOService class though, which is the issue I ran into.

**Comment by ben9923** [comment]
@kprinssu There are a couple of similar cases in the other kexts, I can push those too.

@1Revenger1 Isn't `log` broken (i.e. not showing all kext logs)?
Otherwaise why we ask users for `dmesg` output by stretching `msgbuf`?

**Comment by 1Revenger1** [comment]
> @1Revenger1 Isn't `log` broken (i.e. not showing all kext logs)?
> Otherwaise why we ask users for `dmesg` output by stretching `msgbuf`?

Useful for streaming data in real time. Although that's broke half the time as well lol.

**Pull request merged**
