### PR TITLE
Add AMD support

### PR DESCRIPTION
**Pull request by ChefKissInc**

### CODE REVIEW

**Comment by ChefKissInc** [comment]
Issue has been resolved with latest commit. Trackpad work via polling mode

**Review by kprinssu — APPROVED** [review]
Thanks @ChefKissInc 

Great work with adding AMD support!

**Comment by andreszerocross** [comment]
image


How can i get artifact?? Can voodooI2C team enable this features?? I don't know. I can't build it by myself :(

**Comment by ChefKissInc** [comment]
this will not work yet, voodoogpio changes have not been merged yet

**Comment by kprinssu** [comment]
Spamming PRs for help is neither helpful nor contributing to original work that was done.

I am locking this PR as the discussion has run its course.

**Pull request merged**
