### PR TITLE
Separate VoodooI2CPCILakeController

### LINKED ISSUE #368: VoodooI2CPCIController does not support 8th Gen Intel Core Processor LPSS: I2C Controller # 2
Hello!
Add to support 8th Gen Intel Core Processor LPSS: I2C Controller # 2 (8086 9DEA 17AA 3805 Intel Corporation)
Serial bus controlle CI0@0/I2C2@15,2 pci8086,9dea    PciRoot(0x0)/Pci(0x15,0x2)

    "DevicePath" : "PciRoot(0x0)\/Pci(0x15,0x2)",
    "DeviceName" : "???",
    "ShadowDevice" : 40426,
    "IORegPath" : "IOService:\/AppleACPIPlatformExpert\/PCI0@0\/AppleACPIPCI\/I2C2@15,2",
    "SlotName" : "Internal@0,21,2",
    "ASPM" : "Disabled",
    "IORegIOName" : "pci8086,9dea",
    "ClassCode" : 819200,
    "Address" : 1376258,
    "PCIDebug" : "00:15.2",
    "VendorName" : "Intel Corporation",
    "ClassName" : "Serial bus controller",
    "SubDeviceID" : 14341,
    "VendorID" : 32902,
    "IORegName" : "\/PCI0@0\/I2C2@15,2",
    "Model" : "???",
    "SubClassName" : "???",
    "SubVendorID" : 6058,
    "ShadowVendor" : 32902,
    "DeviceID" : 40426,
    "BundleID" : "com.apple.driver.AppleACPIPlatform"

### PR DESCRIPTION
**Pull request by zhen-zen**
Quick implementation for #363.
Need testing for CML/ICL (should work without issue).
Anyone has a better name for the inherited controller?

Also close #368.

### CODE REVIEW

**Comment by KhoraLee** [comment]
Both CML and ICL is Intel's 10th Generation Core. So how about call VoodooI2CPCI10THGENController?

~looks a little bit long...~

**Comment by kprinssu** [comment]
@KhoraLee No, I would prefer not to call it that. It's best to use Intel's naming convention here, ` VoodooI2CPCIceLakeController.cpp`

Additionally, @zhen-zen we should move the other chipsets into their own respective classes.

Tagging @ben9923 @alexandred as they more familiar with this portion of code than myself.

**Comment by zhen-zen** [comment]
What about just distinguish them in info.plist? All "Point" or "Lake" controllers share their classes respectively.

**Comment by ben9923** [comment]
I think we can just call the classes by the earliest matching generation.
I.e. Skylake for everything prior to CML, and CometLake for CML+ICL.

**Comment by zhen-zen** [comment]
Skylake does make sense but Comet Lake is often considered the same generation for 14nm architecture.
And also prior to Comet Lake, the I2C Controllers are named after their PCH.

VoodooI2CACPIController
- INT33C2 and INT33C3 - Haswell era / 8 series
Lynx Point
- INT3432 and INT3433 - Broadwell era / 9 series
Wildcat Point

VoodooI2CPCIController
- pci8086,9d60, pci8086,9d61, pci8086,9d62 and pci8086,9d63 - Skylake era / 100 series
Sunrise Point-LP
- pci8086,a160 and pci8086,a161 - Kaby Lake era / 100 series
Sunrise Point-H
- pci8086,9de8 and pci8086,9de9 - Cannon Lake/Whiskey Lake era / 300 series
Cannon Point-LP
- pci8086,a368, pci8086,a369, pci8086,a36a and pci8086,a36b - Coffee Lake era / 300 series
Cannon Point-H

Need additional D0 patch
- pci8086,2e8, pci8086,2e9, pci8086,6e8 and pci8086,6e9- Comet Lake era / 400 series
Comet Lake-LP/H
- pci8086,34e8, pci8086,34e9- Ice Lake era / no desktop processors announced yet
Ice Lake-LP

**Review by ben9923 — CHANGES_REQUESTED** [review]
I like the usage of IOPCIDevice matching :)
Just couldn't understand the duplicate personality for the same class, with no different properties.

**Comment by kprinssu** [comment]
This PR is good to go. However, we need to merge in https://github.com/VoodooI2C/VoodooI2C/pull/365/files before we can go ahead.

**Review by ben9923 — APPROVED** [review]

**Comment by marianopela** [comment]
@zhen-zen IIRC the notion.so author should be @phu54321 (he may correct me if I'm wrong)

**Comment by zhen-zen** [comment]
> @zhen-zen IIRC the notion.so author should be @phu54321 (he may correct me if I'm wrong)

Thanks!

**Comment by phu54321** [comment]
Thanks for clarification :)

**Review by kprinssu — APPROVED** [review]

**Pull request merged**
