### PR TITLE
Update VoodooI2CPCIController for Ice Lake PCI IDs

### PR DESCRIPTION
**Pull request by KhoraLee**
#342

### CODE REVIEW

**Comment by Goshin** [comment]
Can it be simplified with `sscanf`?

```c++
int pre, post;
if (sscanf(physical_device.name, "pci8086,%de%d", &pre, &post) == 2) {
    // do the patch here
}
```

**Comment by KhoraLee** [comment]
@Goshin Great Idea!

**Comment by kprinssu** [comment]
Thanks @KhoraLee and @Goshin. Revised code looks much better, except for this one small bug:

`"pci8086,%de%d"` should be `"pci8086,3%de%d".

**Comment by alexandred** [comment]
The PR looks fine to me but is not very modular. Personally I would subclass VoodooI2CPCI for each generation (so VoodooI2CPCICometLake etc) and have the work of checking device ID done by IOKit’s matching process. Each device’s patch would then be isolated to its own PCI subclass. Doing it this way prevents clutter and unnecessary code execution (since these checks are being performed on all systems regardless of their architecture).

**Comment by kprinssu** [comment]
@alexandred Modularising that seems a bit outside the scope of this PR, I suggest that we should address in a subsequent one?

**Comment by alexandred** [comment]
Sure, my only point was that I would favour modularisation instead of merging this PR. The way this is going is that for every future architecture we might need a patch and I’d rather nip this is in the bud now rather than in the future when we have several patches cluttering the code.

That being said I don’t have time to do this myself so I am happy to merge this PR to provide the desired functionality asap.

**Pull request merged**
